export interface SocialMediaLinks {
    facebook?: string;
    twitter?: string;
    instagram?: string;
    linkedin?: string;
    youtube?: string;
    tiktok?: string;
    pinterest?: string;
    reddit?: string;
    snapchat?: string;
    github?: string;
    stackoverflow?: string;
    dribbble?: string;
    behance?: string;
    tumblr?: string;
    vimeo?: string;
    soundcloud?: string;
    deviantart?: string;
    twitch?: string;
    discord?: string;
    steam?: string;
    wechat?: string;
    vk?: string;
    website?: string;
};